project:
  type: book
  output-dir: docs

book:
  title: "SEAwise Tutorial WP6: Multi-Criteria Decision Analysis"
  author: "Andrea Schiavo"
  chapters:
    - index.qmd
    - 01_Theory.qmd
    - 02_Theory Seawise_example.qmd
    - 03_R-script.qmd
    - 04_Visualization.qmd
    - 05_genOptionsFile.qmd

format:
  html:
    theme: cosmo       # tema grafico
    toc: true          # table of contents
    number-sections: false
    code-copy: true    # pulsante per copiare codice
resources:
  - png/*
